- .gitattributes
- tsconfig.json
Might give a Merge Conflict with the other one, I didn't think of that properly, I'll keep this in mind on next MR
> Fixes #1, removed few entries from tsconfig.json

- config.js
- dist/typings/http-client.d.ts
- gulpfile.js
- package.json
- tsconfig.json
Is this okay? Changed few things and now npm run build does work and it also copies typings
> Distribute typings

- .gitignore
- src/main.ts
- test/HttpApiClientTest.ts
> Implement http api client

- src/main.ts
> fix(Service): add missing export for Service-class

- gulpfile.js
> fix(bundle.d.ts): add missing declarations

- config.js
- package.json
- src/FetchClient.ts
- src/ServiceClient.ts
- tslint.json
feat(TypeScript): Updated to 2.1 
Updated most dependencies in the process.
> Typescript 2.1

- karma.conf.js
- package.json
> test(typescript): Update karma-typescript to use version 2.1.6

- package.json
> chore(package): update validate-commit-msg to version 2.10.1

- src/Client.spec.ts
- src/Client.ts
- src/Service.spec.ts
- src/Service.ts
- src/Stack.spec.ts
- src/Stack.ts
- src/internal/formatting.spec.ts
- src/internal/formatting.ts
- src/middlewares/Fetch.spec.ts
- src/middlewares/Fetch.ts
- src/middlewares/Mock.spec.ts
- src/middlewares/Mock.ts
- src/middlewares/index.ts
- wallaby.js
fixes #65 
- Add Mock middleware
- Add tests for Mock middleware
- Question (do we start doing documentation too?)
- Need help: do we declare our own Response? Is it same as IResponse?
> 65 mock middleware

- package.json
> chore(package): update @types/node to version 7.0.2

- package.json
- src/internal/formatting.spec.ts
https://greenkeeper.io/
Fixes #83
> chore(package): update @types/node to version 7.0.8

- package.json
https://greenkeeper.io/
Fixes #81
> chore(package): update karma-firefox-launcher to version 1.0.1

- src/middlewares/Mock.spec.ts
Removed the delay checking part because Firefox is not accurate.
> test(mock): Remove the setTimeout check from test

- package.json
https://greenkeeper.io/
Fixes #85
> chore(package): update tslint-microsoft-contrib to version 4.0.1

- package.json
https://greenkeeper.io/
Fixes #84
> chore(package): update @types/jasmine to version 2.5.46

- README.md
> fix(README): Made nodejs comment more important!

- package.json
should pass once #122 is merged
closes #120
> chore(package): update node-fetch to version 1.7.0

- .travis.yml
> chore(greenkeeper): add greenkeeper lock file support

- .gitignore
- .npmignore
- .travis.yml
- JestBootstrap.ts
- package-lock.json
- package.json
- src/middlewares/CacheMiddleware.spec.ts
- tsconfig.json
> test(*): use jest instead of karma

- package.json
> chore(package): update pre-push hook

- src/middlewares/ContentTypeMiddleware.spec.ts
- src/middlewares/ContentTypeMiddleware.ts
- src/middlewares/index.ts
> test(ContentTypeMiddleware): add content-type middleware
